export interface DailySentence {
  thai: string
  pinyin: string
  zh: string
  context: string
}

export const DAILY_SENTENCES: DailySentence[] = [
  // 👋 打招呼 & 自我介紹
  { thai: 'สวัสดีค่ะ', pinyin: 'sà-wàt-dii kâ', zh: '你好', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันชื่อ___ค่ะ', pinyin: 'chăn chûue ___ kâ', zh: '我叫___', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันมาจากไต้หวันค่ะ', pinyin: 'chăn maa jàak dtâi-wăn kâ', zh: '我來自台灣', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันไม่ได้มาจากจีนค่ะ มาจากไต้หวัน', pinyin: 'chăn mâi dâi maa jàak jiin kâ maa jàak dtâi-wăn', zh: '我不是從中國來的，我來自台灣', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ยินดีที่ได้รู้จักค่ะ', pinyin: 'yin-dii tîi dâi rúu-jàk kâ', zh: '很高興認識你', context: '👋 打招呼 & 自我介紹' },
  { thai: 'คุณชื่ออะไรคะ', pinyin: 'kun chûue à-rai ká', zh: '你叫什麼名字？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'อายุเท่าไหร่คะ', pinyin: 'aa-yú tâo-rài ká', zh: '你幾歲？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันอายุ___ปีค่ะ', pinyin: 'chăn aa-yú ___ bpii kâ', zh: '我___歲', context: '👋 打招呼 & 自我介紹' },
  { thai: 'คุณทำงานอะไรคะ', pinyin: 'kun tam-ngaan à-rai ká', zh: '你做什麼工作？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'มาเที่ยวไทยครั้งแรกค่ะ', pinyin: 'maa tîao tai kráng-râek kâ', zh: '這是我第一次來泰國', context: '👋 打招呼 & 自我介紹' },
  { thai: 'มาไทยครั้งนี้มากี่วันคะ', pinyin: 'maa tai kráng-níi maa gìi wan ká', zh: '這次來泰國待幾天？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'มาเที่ยวค่ะ', pinyin: 'maa tîao kâ', zh: '來玩的', context: '👋 打招呼 & 自我介紹' },
  { thai: 'สบายดีไหมคะ', pinyin: 'sà-baai dii mái ká', zh: '你好嗎？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'นานแค่ไหนแล้วคะที่อยู่ที่นี่', pinyin: 'naan kâe nǎi láew ká tîi yùu tîi-nîi', zh: '你在這裡多久了？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันเรียนภาษาไทยอยู่ค่ะ', pinyin: 'chăn rian paa-sǎa tai yùu kâ', zh: '我正在學英文', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ภาษาไทยยากมากค่ะ', pinyin: 'paa-sǎa tai yâak mâak kâ', zh: '英文好難', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันพูดไทยได้นิดหน่อยค่ะ', pinyin: 'chăn pûut tai dâi nít-nòi kâ', zh: '我會說一點點英文', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ช่วยสอนฉันหน่อยได้ไหมคะ', pinyin: 'chûay sŏn chăn nòi dâi mái ká', zh: '可以教我嗎？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'คุณอยู่ที่นี่นานแค่ไหนแล้วคะ', pinyin: 'kun yùu tîi-nîi naan kâe nǎi láew ká', zh: '你在這裡多久了？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันทำงานเป็นนักเรียนค่ะ', pinyin: 'chăn tam-ngaan bpen nák-rian kâ', zh: '我是學生', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันเป็นฟรีแลนซ์ค่ะ', pinyin: 'chăn bpen free-laen kâ', zh: '我是自由工作者', context: '👋 打招呼 & 自我介紹' },
  { thai: 'แล้วคุณล่ะคะ', pinyin: 'láew kun lâ ká', zh: '那你呢？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ติดต่อกันได้ยังไงคะ', pinyin: 'dtìt-dtòr gan dâi yang-ngai ká', zh: '怎麼保持聯絡？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ขอ Line ได้ไหมคะ', pinyin: 'kŏr Line dâi mái ká', zh: '可以給我 Line 嗎？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ขอ IG ได้ไหมคะ', pinyin: 'kŏr IG dâi mái ká', zh: '可以給我 IG 嗎？', context: '👋 打招呼 & 自我介紹' },
  { thai: 'เพิ่มเพื่อนได้เลยค่ะ', pinyin: 'pûem pûean dâi loey kâ', zh: '可以加我好友', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันมาคนเดียวค่ะ', pinyin: 'chăn maa kon-diao kâ', zh: '我一個人來', context: '👋 打招呼 & 自我介紹' },
  { thai: 'มากับเพื่อนค่ะ', pinyin: 'maa gàp pûean kâ', zh: '跟朋友一起來', context: '👋 打招呼 & 自我介紹' },
  { thai: 'นี่เป็นทริปแรกของฉันค่ะ', pinyin: 'nîi bpen tríp râek kŏng chăn kâ', zh: '這是我第一次旅行', context: '👋 打招呼 & 自我介紹' },
  { thai: 'ฉันชอบไทยมากค่ะ', pinyin: 'chăn chôp tai mâak kâ', zh: '我非常喜歡泰國', context: '👋 打招呼 & 自我介紹' },

  // 🍜 餐廳 & 點餐
  { thai: 'ขอเมนูด้วยค่ะ', pinyin: 'kŏr meh-nuu dûay kâ', zh: '請給我菜單', context: '🍜 餐廳 & 點餐' },
  { thai: 'มีอะไรแนะนำบ้างคะ', pinyin: 'mii à-rai náe-nam bâang ká', zh: '有什麼推薦的嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'อะไรขายดีที่สุดคะ', pinyin: 'à-rai kǎai dii tîi-sùt ká', zh: '什麼賣最好？', context: '🍜 餐廳 & 點餐' },
  { thai: 'ไม่ใส่ผักชีค่ะ', pinyin: 'mâi sài pàk-chii kâ', zh: '不要加香菜', context: '🍜 餐廳 & 點餐' },
  { thai: 'ไม่เผ็ดค่ะ', pinyin: 'mâi pèt kâ', zh: '不要辣', context: '🍜 餐廳 & 點餐' },
  { thai: 'เผ็ดน้อยค่ะ', pinyin: 'pèt nói kâ', zh: '少辣', context: '🍜 餐廳 & 點餐' },
  { thai: 'เผ็ดมากค่ะ', pinyin: 'pèt mâak kâ', zh: '很辣', context: '🍜 餐廳 & 點餐' },
  { thai: 'ข้างในมีอะไรบ้างคะ', pinyin: 'kâang-nai mii à-rai bâang ká', zh: '裡面有什麼食材？', context: '🍜 餐廳 & 點餐' },
  { thai: 'ฉันแพ้อาหารทะเลค่ะ', pinyin: 'chăn páe aa-hǎan tá-lee kâ', zh: '我對海鮮過敏', context: '🍜 餐廳 & 點餐' },
  { thai: 'ฉันกินเจค่ะ', pinyin: 'chăn gin jee kâ', zh: '我吃素（齋）', context: '🍜 餐廳 & 點餐' },
  { thai: 'ขอน้ำเปล่าด้วยค่ะ', pinyin: 'kŏr nám bplào dûay kâ', zh: '請給我白開水', context: '🍜 餐廳 & 點餐' },
  { thai: 'เก็บเงินด้วยค่ะ', pinyin: 'gèp ngern dûay kâ', zh: '結帳', context: '🍜 餐廳 & 點餐' },
  { thai: 'รับบัตรเครดิตไหมคะ', pinyin: 'ráp bàt-kreh-dìt mái ká', zh: '可以刷卡嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'อร่อยมากค่ะ', pinyin: 'à-ròi mâak kâ', zh: '非常好吃', context: '🍜 餐廳 & 點餐' },
  { thai: 'นั่งที่ไหนได้บ้างคะ', pinyin: 'nâng tîi-nǎi dâi bâang ká', zh: '可以坐哪裡？', context: '🍜 餐廳 & 點餐' },
  { thai: 'ขอโต๊ะสำหรับสองคนค่ะ', pinyin: 'kŏr dtó săm-ràp sŏng kon kâ', zh: '兩位', context: '🍜 餐廳 & 點餐' },
  { thai: 'มีที่นั่งไหมคะ', pinyin: 'mii tîi-nâng mái ká', zh: '有位子嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'รอนานไหมคะ', pinyin: 'ror naan mái ká', zh: '要等很久嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'สั่งได้เลยไหมคะ', pinyin: 'sàng dâi loey mái ká', zh: '可以點餐了嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'ขอเพิ่มอีกจานได้ไหมคะ', pinyin: 'kŏr pûem ìik jaan dâi mái ká', zh: '可以再加一份嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'อันนี้คืออะไรคะ', pinyin: 'an-níi kuue à-rai ká', zh: '這個是什麼？', context: '🍜 餐廳 & 點餐' },
  { thai: 'หวานน้อยหน่อยได้ไหมคะ', pinyin: 'wǎan nói nòi dâi mái ká', zh: '可以少糖嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'ไม่ใส่น้ำตาลค่ะ', pinyin: 'mâi sài nám-dtaan kâ', zh: '不加糖', context: '🍜 餐廳 & 點餐' },
  { thai: 'ใส่น้ำแข็งด้วยค่ะ', pinyin: 'sài nám-kăeng dûay kâ', zh: '加冰', context: '🍜 餐廳 & 點餐' },
  { thai: 'ไม่ใส่น้ำแข็งค่ะ', pinyin: 'mâi sài nám-kăeng kâ', zh: '不加冰', context: '🍜 餐廳 & 點餐' },
  { thai: 'มีมังสวิรัติไหมคะ', pinyin: 'mii mang-sà-wí-rát mái ká', zh: '有素食選項嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'ข้าวหรือขนมปังคะ', pinyin: 'kâao rŭe kà-nŏm-bpang ká', zh: '要飯還是麵包？', context: '🍜 餐廳 & 點餐' },
  { thai: 'แยกจ่ายได้ไหมคะ', pinyin: 'yâek jàai dâi mái ká', zh: '可以分開付嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'จ่ายด้วย QR Code ได้ไหมคะ', pinyin: 'jàai dûay QR Code dâi mái ká', zh: '可以用 QR Code 付款嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'มีส้อมไหมคะ', pinyin: 'mii sôm mái ká', zh: '有叉子嗎？', context: '🍜 餐廳 & 點餐' },
  { thai: 'ขอตะเกียบด้วยค่ะ', pinyin: 'kŏr dtà-gìap dûay kâ', zh: '請給我筷子', context: '🍜 餐廳 & 點餐' },
  { thai: 'อาหารยังไม่มาค่ะ', pinyin: 'aa-hǎan yang mâi maa kâ', zh: '餐點還沒來', context: '🍜 餐廳 & 點餐' },

  // 🚕 交通 & 移動
  { thai: 'ไปที่___ค่ะ', pinyin: 'bpai tîi ___ kâ', zh: '我要去___', context: '🚕 交通 & 移動' },
  { thai: 'ขับตรงไปค่ะ', pinyin: 'kàp dtrong bpai kâ', zh: '直走', context: '🚕 交通 & 移動' },
  { thai: 'เลี้ยวซ้ายค่ะ', pinyin: 'líao sáai kâ', zh: '左轉', context: '🚕 交通 & 移動' },
  { thai: 'เลี้ยวขวาค่ะ', pinyin: 'líao kwǎa kâ', zh: '右轉', context: '🚕 交通 & 移動' },
  { thai: 'จอดตรงนี้ได้เลยค่ะ', pinyin: 'jòrt dtrong-níi dâi loey kâ', zh: '停這裡就好', context: '🚕 交通 & 移動' },
  { thai: 'ใกล้แค่ไหนคะ', pinyin: 'glâi kâe nǎi ká', zh: '有多近？', context: '🚕 交通 & 移動' },
  { thai: 'ไปสนามบินได้ยังไงคะ', pinyin: 'bpai sà-nǎam-bin dâi yang-ngai ká', zh: '怎麼去機場？', context: '🚕 交通 & 移動' },
  { thai: 'นั่งรถตุ๊กตุ๊กได้ไหมคะ', pinyin: 'nâng rót dtúk-dtúk dâi mái ká', zh: '可以搭嘟嘟車嗎？', context: '🚕 交通 & 移動' },
  { thai: 'เรียก Grab ให้หน่อยได้ไหมคะ', pinyin: 'rîak Grab hâi nòi dâi mái ká', zh: '可以幫我叫 Grab 嗎？', context: '🚕 交通 & 移動' },
  { thai: 'คิดเท่าไหร่คะ', pinyin: 'kít tâo-rài ká', zh: '要多少錢？', context: '🚕 交通 & 移動' },
  { thai: 'ถึงแล้วค่ะ', pinyin: 'tŭeng láew kâ', zh: '到了', context: '🚕 交通 & 移動' },
  { thai: 'รอสักครู่นะคะ', pinyin: 'ror sàk krûu ná kâ', zh: '請等一下', context: '🚕 交通 & 移動' },
  { thai: 'ที่นี่คือที่ไหนคะ', pinyin: 'tîi-nîi kuue tîi-nǎi ká', zh: '這裡是哪裡？', context: '🚕 交通 & 移動' },
  { thai: 'ห่างจากที่นี่ไกลไหมคะ', pinyin: 'hàang jàak tîi-nîi glai mái ká', zh: '離這裡遠嗎？', context: '🚕 交通 & 移動' },
  { thai: 'เดินไปได้ไหมคะ', pinyin: 'dern bpai dâi mái ká', zh: '可以走路去嗎？', context: '🚕 交通 & 移動' },
  { thai: 'ขึ้นรถเมล์ที่ไหนคะ', pinyin: 'kûen rót-mee tîi-nǎi ká', zh: '在哪裡搭公車？', context: '🚕 交通 & 移動' },
  { thai: 'รถไฟฟ้าอยู่ที่ไหนคะ', pinyin: 'rót-fai-fáa yùu tîi-nǎi ká', zh: 'BTS 捷運在哪裡？', context: '🚕 交通 & 移動' },
  { thai: 'ซื้อตั๋วรถไฟฟ้าที่ไหนคะ', pinyin: 'súue dtǔa rót-fai-fáa tîi-nǎi ká', zh: '在哪裡買捷運票？', context: '🚕 交通 & 移動' },
  { thai: 'ลงสถานีไหนคะ', pinyin: 'long sà-tǎa-nii nǎi ká', zh: '在哪一站下車？', context: '🚕 交通 & 移動' },
  { thai: 'เปลี่ยนสายที่ไหนคะ', pinyin: 'bplìan sǎai tîi-nǎi ká', zh: '在哪裡換線？', context: '🚕 交通 & 移動' },
  { thai: 'นั่งแท็กซี่ดีกว่าไหมคะ', pinyin: 'nâng táek-sîi dii gwàa mái ká', zh: '搭計程車比較好嗎？', context: '🚕 交通 & 移動' },
  { thai: 'เปิดมิเตอร์ด้วยนะคะ', pinyin: 'bpùet mí-dteu dûay ná kâ', zh: '請開錶計費', context: '🚕 交通 & 移動' },
  { thai: 'ไม่ต้องทอนค่ะ', pinyin: 'mâi dtông ton kâ', zh: '不用找零', context: '🚕 交通 & 移動' },
  { thai: 'จอดตรงนั้นเลยได้ไหมคะ', pinyin: 'jòrt dtrong-nán loey dâi mái ká', zh: '可以停在那裡嗎？', context: '🚕 交通 & 移動' },
  { thai: 'ช่วยรอสักครู่ได้ไหมคะ', pinyin: 'chûay ror sàk krûu dâi mái ká', zh: '可以等我一下嗎？', context: '🚕 交通 & 移動' },
  { thai: 'ติดต่อกันทาง Line ได้ไหมคะ', pinyin: 'dtìt-dtòr gan taang Line dâi mái ká', zh: '可以用 Line 聯絡嗎？', context: '🚕 交通 & 移動' },
  { thai: 'แผนที่ช่วยได้ไหมคะ', pinyin: 'pǎen-tîi chûay dâi mái ká', zh: '地圖能幫上忙嗎？', context: '🚕 交通 & 移動' },
  { thai: 'ขึ้นเครื่องกี่โมงคะ', pinyin: 'kûen krûuang gìi moong ká', zh: '幾點登機？', context: '🚕 交通 & 移動' },
  { thai: 'ประตูขึ้นเครื่องอยู่ที่ไหนคะ', pinyin: 'bprà-dtuu kûen krûuang yùu tîi-nǎi ká', zh: '登機門在哪裡？', context: '🚕 交通 & 移動' },
  { thai: 'รถติดมากค่ะ', pinyin: 'rót dtìt mâak kâ', zh: '很塞車', context: '🚕 交通 & 移動' },

  // 🛍️ 購物 & 殺價
  { thai: 'นี่ราคาเท่าไหร่คะ', pinyin: 'nîi raa-kaa tâo-rài ká', zh: '這個多少錢？', context: '🛍️ 購物 & 殺價' },
  { thai: 'มีสีอื่นไหมคะ', pinyin: 'mii sĭi ùuen mái ká', zh: '有其他顏色嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'มีไซส์ใหญ่กว่านี้ไหมคะ', pinyin: 'mii sáis yài gwàa níi mái ká', zh: '有更大的尺寸嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'ลองได้ไหมคะ', pinyin: 'lorng dâi mái ká', zh: '可以試穿嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'ลดได้ไหมคะ', pinyin: 'lót dâi mái ká', zh: '可以便宜一點嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'แพงไปค่ะ', pinyin: 'paeng bpai kâ', zh: '太貴了', context: '🛍️ 購物 & 殺價' },
  { thai: 'ถูกกว่านี้ได้ไหมคะ', pinyin: 'tùuk gwàa níi dâi mái ká', zh: '可以更便宜嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'เอาอันนี้ค่ะ', pinyin: 'ao an-níi kâ', zh: '我要這個', context: '🛍️ 購物 & 殺價' },
  { thai: 'มีของแท้ไหมคะ', pinyin: 'mii kŏng-táe mái ká', zh: '有賣真品嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'ขอถุงด้วยค่ะ', pinyin: 'kŏr tŭng dûay kâ', zh: '請給我袋子', context: '🛍️ 購物 & 殺價' },
  { thai: 'มีส่วนลดไหมคะ', pinyin: 'mii sùan-lót mái ká', zh: '有折扣嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'ซื้อสองชิ้นลดได้ไหมคะ', pinyin: 'súue sŏng chín lót dâi mái ká', zh: '買兩件可以打折嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'มีขายไหมคะ', pinyin: 'mii kǎai mái ká', zh: '有賣嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'อันนี้ทำจากอะไรคะ', pinyin: 'an-níi tam jàak à-rai ká', zh: '這個是什麼材質？', context: '🛍️ 購物 & 殺價' },
  { thai: 'มีไซส์เล็กกว่านี้ไหมคะ', pinyin: 'mii sáis lék gwàa níi mái ká', zh: '有更小的尺寸嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'ห้องลองเสื้ออยู่ที่ไหนคะ', pinyin: 'hông lorng sûea yùu tîi-nǎi ká', zh: '試衣間在哪裡？', context: '🛍️ 購物 & 殺價' },
  { thai: 'ลองได้กี่ตัวคะ', pinyin: 'lorng dâi gìi dtuay ká', zh: '可以試幾件？', context: '🛍️ 購物 & 殺價' },
  { thai: 'พอดีค่ะ', pinyin: 'por-dii kâ', zh: '剛好合身', context: '🛍️ 購物 & 殺價' },
  { thai: 'ใหญ่ไปค่ะ', pinyin: 'yài bpai kâ', zh: '太大了', context: '🛍️ 購物 & 殺價' },
  { thai: 'เล็กไปค่ะ', pinyin: 'lék bpai kâ', zh: '太小了', context: '🛍️ 購物 & 殺價' },
  { thai: 'สวยมากค่ะ', pinyin: 'sŭay mâak kâ', zh: '好漂亮', context: '🛍️ 購物 & 殺價' },
  { thai: 'ซื้อสองชิ้นได้ราคาพิเศษไหมคะ', pinyin: 'súue sŏng chín dâi raa-kaa pí-sèet mái ká', zh: '買兩件有特別價嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'แพ็คให้ด้วยได้ไหมคะ', pinyin: 'páek hâi dûay dâi mái ká', zh: '可以幫我包裝嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'เป็นของฝากค่ะ', pinyin: 'bpen kŏng-fàak kâ', zh: '這是伴手禮', context: '🛍️ 購物 & 殺價' },
  { thai: 'มีรับประกันไหมคะ', pinyin: 'mii ráp-bprà-gan mái ká', zh: '有保固嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'เปลี่ยนได้ไหมคะ', pinyin: 'bplìan dâi mái ká', zh: '可以換貨嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'คืนได้ไหมคะ', pinyin: 'kuuen dâi mái ká', zh: '可以退貨嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'จ่ายพร้อมเพย์ได้ไหมคะ', pinyin: 'jàai Promptpay dâi mái ká', zh: '可以用 PromptPay 付款嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'ของแท้รับประกันไหมคะ', pinyin: 'kŏng-táe ráp-bprà-gan mái ká', zh: '保證是真品嗎？', context: '🛍️ 購物 & 殺價' },
  { thai: 'ขอใบเสร็จด้วยค่ะ', pinyin: 'kŏr bai-sèt dûay kâ', zh: '請給我收據', context: '🛍️ 購物 & 殺價' },

  // 🏨 住宿 & 飯店
  { thai: 'มีห้องว่างไหมคะ', pinyin: 'mii hông wâang mái ká', zh: '有空房嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'จองห้องพักไว้แล้วค่ะ', pinyin: 'jorng hông-pák wái láew kâ', zh: '我已經訂房了', context: '🏨 住宿 & 飯店' },
  { thai: 'ห้องน้ำอยู่ที่ไหนคะ', pinyin: 'hông-nám yùu tîi-nǎi ká', zh: '廁所在哪裡？', context: '🏨 住宿 & 飯店' },
  { thai: 'ที่นี่มีอินเทอร์เน็ตไหมคะ', pinyin: 'tîi-nîi mii in-ter-nèt mái ká', zh: '這裡有網路嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'รหัส WiFi คืออะไรคะ', pinyin: 'rá-hàt WiFi kuue à-rai ká', zh: 'WiFi 密碼是什麼？', context: '🏨 住宿 & 飯店' },
  { thai: 'เช็คเอาท์กี่โมงคะ', pinyin: 'chék-ao gìi moong ká', zh: '幾點退房？', context: '🏨 住宿 & 飯店' },
  { thai: 'ฝากกระเป๋าได้ไหมคะ', pinyin: 'fàak grà-bpǎo dâi mái ká', zh: '可以寄放行李嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'ขอผ้าเช็ดตัวเพิ่มได้ไหมคะ', pinyin: 'kŏr pâa-chét-dtuay pûem dâi mái ká', zh: '可以再給我毛巾嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'แอร์เสียค่ะ', pinyin: 'ae sĭa kâ', zh: '冷氣壞了', context: '🏨 住宿 & 飯店' },
  { thai: 'ขอใบเสร็จด้วยค่ะ', pinyin: 'kŏr bai-sèt dûay kâ', zh: '請給我收據', context: '🏨 住宿 & 飯店' },
  { thai: 'เช็คอินได้กี่โมงคะ', pinyin: 'chék-in dâi gìi moong ká', zh: '幾點可以入住？', context: '🏨 住宿 & 飯店' },
  { thai: 'เช็คอินก่อนเวลาได้ไหมคะ', pinyin: 'chék-in gòn weh-laa dâi mái ká', zh: '可以提早入住嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'ห้องมีวิวทะเลไหมคะ', pinyin: 'hông mii wiw tá-lee mái ká', zh: '房間有海景嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'ขอห้องชั้นสูงได้ไหมคะ', pinyin: 'kŏr hông chán sŭung dâi mái ká', zh: '可以要高樓層嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'อาหารเช้ารวมอยู่ไหมคะ', pinyin: 'aa-hǎan cháo ruam yùu mái ká', zh: '有含早餐嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'อาหารเช้าอยู่ที่ไหนคะ', pinyin: 'aa-hǎan cháo yùu tîi-nǎi ká', zh: '早餐在哪裡？', context: '🏨 住宿 & 飯店' },
  { thai: 'มีสระว่ายน้ำไหมคะ', pinyin: 'mii sà-wâai-nám mái ká', zh: '有游泳池嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'สระว่ายน้ำเปิดกี่โมงคะ', pinyin: 'sà-wâai-nám bpùet gìi moong ká', zh: '游泳池幾點開？', context: '🏨 住宿 & 飯店' },
  { thai: 'มีบริการรับส่งสนามบินไหมคะ', pinyin: 'mii bor-rí-gaan ráp-sòng sà-nǎam-bin mái ká', zh: '有機場接送服務嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'เรียกแท็กซี่ให้หน่อยได้ไหมคะ', pinyin: 'rîak táek-sîi hâi nòi dâi mái ká', zh: '可以幫我叫計程車嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'ของในตู้เย็นคิดเงินไหมคะ', pinyin: 'kŏng nai dtûu-yen kít-ngern mái ká', zh: '冰箱裡的東西要收費嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'เปลี่ยนผ้าปูที่นอนให้ด้วยได้ไหมคะ', pinyin: 'bplìan pâa-bpuu-tîi-non hâi dûay dâi mái ká', zh: '可以換床單嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'ลืมกุญแจไว้ในห้องค่ะ', pinyin: 'luuem gun-jae wái nai hông kâ', zh: '我把鑰匙忘在房間裡了', context: '🏨 住宿 & 飯店' },
  { thai: 'ห้องข้างๆเสียงดังมากค่ะ', pinyin: 'hông kâang-kâang sĭang-dang mâak kâ', zh: '隔壁房間很吵', context: '🏨 住宿 & 飯店' },
  { thai: 'ขอเปลี่ยนห้องได้ไหมคะ', pinyin: 'kŏr bplìan hông dâi mái ká', zh: '可以換房間嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'น้ำไม่ร้อนค่ะ', pinyin: 'nám mâi rón kâ', zh: '水不熱', context: '🏨 住宿 & 飯店' },
  { thai: 'ไฟในห้องน้ำเสียค่ะ', pinyin: 'fai nai hông-nám sĭa kâ', zh: '浴室燈壞了', context: '🏨 住宿 & 飯店' },
  { thai: 'เลทเช็คเอาท์ได้ไหมคะ', pinyin: 'lét chék-ao dâi mái ká', zh: '可以延遲退房嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'ชั้นนี้มีเครื่องซักผ้าไหมคะ', pinyin: 'chán-níi mii krûuang-sák-pâa mái ká', zh: '這層有洗衣機嗎？', context: '🏨 住宿 & 飯店' },
  { thai: 'ขอหมอนเพิ่มได้ไหมคะ', pinyin: 'kŏr mŏn pûem dâi mái ká', zh: '可以多給我一個枕頭嗎？', context: '🏨 住宿 & 飯店' },

  // 🏥 緊急狀況 & 求助
  { thai: 'ช่วยด้วยค่ะ', pinyin: 'chûay dûay kâ', zh: '請幫幫我！', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ฉันหายค่ะ', pinyin: 'chăn hǎai kâ', zh: '我迷路了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ฉันไม่สบายค่ะ', pinyin: 'chăn mâi sà-baai kâ', zh: '我不舒服', context: '🏥 緊急狀況 & 求助' },
  { thai: 'โรงพยาบาลอยู่ที่ไหนคะ', pinyin: 'rohng-pá-yaa-baan yùu tîi-nǎi ká', zh: '醫院在哪裡？', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ขอโทษค่ะ', pinyin: 'kŏr-tôht kâ', zh: '對不起／不好意思', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ฉันแพ้ยาค่ะ', pinyin: 'chăn páe yaa kâ', zh: '我對藥物過敏', context: '🏥 緊急狀況 & 求助' },
  { thai: 'เรียกตำรวจด้วยค่ะ', pinyin: 'rîak dtam-rùat dûay kâ', zh: '請叫警察', context: '🏥 緊急狀況 & 求助' },
  { thai: 'กระเป๋าหายค่ะ', pinyin: 'grà-bpǎo hǎai kâ', zh: '我的包包不見了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'พูดช้าๆได้ไหมคะ', pinyin: 'pûut cháa-cháa dâi mái ká', zh: '可以說慢一點嗎？', context: '🏥 緊急狀況 & 求助' },
  { thai: 'พูดภาษาอังกฤษได้ไหมคะ', pinyin: 'pûut paa-sǎa ang-grìt dâi mái ká', zh: '你會說英文嗎？', context: '🏥 緊急狀況 & 求助' },
  { thai: 'โทรหาสถานทูตไต้หวันได้ไหมคะ', pinyin: 'toh hăa sà-tǎan-tûut dtâi-wăn dâi mái ká', zh: '可以幫我打給台灣大使館嗎？', context: '🏥 緊急狀況 & 求助' },
  { thai: 'หนังสือเดินทางหายค่ะ', pinyin: 'năng-sŭue dern-taang hǎai kâ', zh: '我的護照不見了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'โทรศัพท์หายค่ะ', pinyin: 'toh-rá-sàp hǎai kâ', zh: '我的手機不見了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ถูกขโมยค่ะ', pinyin: 'tùuk kà-mooy kâ', zh: '我被偷了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ต้องการหมอค่ะ', pinyin: 'dtông-gaan mŏr kâ', zh: '我需要醫生', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ปวดท้องมากค่ะ', pinyin: 'bpùat tóng mâak kâ', zh: '肚子很痛', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ปวดหัวมากค่ะ', pinyin: 'bpùat hŭa mâak kâ', zh: '頭很痛', context: '🏥 緊急狀況 & 求助' },
  { thai: 'มีไข้ค่ะ', pinyin: 'mii kâi kâ', zh: '我發燒了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ท้องเสียค่ะ', pinyin: 'tóng-sĭa kâ', zh: '我拉肚子', context: '🏥 緊急狀況 & 求助' },
  { thai: 'แพ้อาหารค่ะ', pinyin: 'páe aa-hǎan kâ', zh: '食物過敏', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ต้องการยาแก้ปวดค่ะ', pinyin: 'dtông-gaan yaa gâe bpùat kâ', zh: '我需要止痛藥', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ร้านขายยาอยู่ที่ไหนคะ', pinyin: 'ráan-kǎai-yaa yùu tîi-nǎi ká', zh: '藥局在哪裡？', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ฉันเป็นลมค่ะ', pinyin: 'chăn bpen lom kâ', zh: '我昏倒了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'แพ้แมลงค่ะ', pinyin: 'páe má-laeng kâ', zh: '我對蟲子過敏', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ถูกแมลงกัดค่ะ', pinyin: 'tùuk má-laeng gàt kâ', zh: '被蟲咬了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ของหายในโรงแรมค่ะ', pinyin: 'kŏng hǎai nai rohng-raem kâ', zh: '東西在飯店弄丟了', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ขอแจ้งความได้ที่ไหนคะ', pinyin: 'kŏr jâeng-kwaam dâi tîi-nǎi ká', zh: '在哪裡可以報案？', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ประกันภัยครอบคลุมไหมคะ', pinyin: 'bprà-gan-pai krôp-klum mái ká', zh: '保險有理賠嗎？', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ขอเอกสารจากโรงพยาบาลด้วยค่ะ', pinyin: 'kŏr ek-gà-săan jàak rohng-pá-yaa-baan dûay kâ', zh: '請給我醫院的證明文件', context: '🏥 緊急狀況 & 求助' },
  { thai: 'ฉันไม่รู้สึกดีค่ะ', pinyin: 'chăn mâi rúu-sùek dii kâ', zh: '我感覺不太好', context: '🏥 緊急狀況 & 求助' },

  // 💬 日常閒聊
  { thai: 'วันนี้เป็นยังไงบ้างคะ', pinyin: 'wan-níi bpen yang-ngai bâang ká', zh: '今天怎麼樣？', context: '💬 日常閒聊' },
  { thai: 'อากาศร้อนมากเลยค่ะ', pinyin: 'aa-gàat rón mâak loey kâ', zh: '天氣好熱啊', context: '💬 日常閒聊' },
  { thai: 'คิดถึงค่ะ', pinyin: 'kít-tŭeng kâ', zh: '想你了', context: '💬 日常閒聊' },
  { thai: 'สนุกมากค่ะ', pinyin: 'sà-nùk mâak kâ', zh: '很好玩', context: '💬 日常閒聊' },
  { thai: 'น่ารักมากค่ะ', pinyin: 'nâa-rák mâak kâ', zh: '好可愛', context: '💬 日常閒聊' },
  { thai: 'เก่งมากเลยค่ะ', pinyin: 'gèng mâak loey kâ', zh: '好厲害！', context: '💬 日常閒聊' },
  { thai: 'ไม่เป็นไรค่ะ', pinyin: 'mâi bpen rai kâ', zh: '沒關係', context: '💬 日常閒聊' },
  { thai: 'โชคดีนะคะ', pinyin: 'chôhk-dii ná kâ', zh: '祝你好運', context: '💬 日常閒聊' },
  { thai: 'ฝันดีนะคะ', pinyin: 'făn dii ná kâ', zh: '晚安，做個好夢', context: '💬 日常閒聊' },
  { thai: 'แล้วเจอกันนะคะ', pinyin: 'láew jer-gan ná kâ', zh: '再見／下次見', context: '💬 日常閒聊' },
  { thai: 'ขอบคุณมากๆค่ะ', pinyin: 'kòp-kun mâak-mâak kâ', zh: '非常感謝', context: '💬 日常閒聊' },
  { thai: 'ยินดีค่ะ', pinyin: 'yin-dii kâ', zh: '不客氣', context: '💬 日常閒聊' },
  { thai: 'ชอบประเทศไทยมากค่ะ', pinyin: 'chôp bprà-têet-tai mâak kâ', zh: '我很喜歡泰國', context: '💬 日常閒聊' },
  { thai: 'อาหารไทยอร่อยมากค่ะ', pinyin: 'aa-hǎan tai à-ròi mâak kâ', zh: '泰國食物好好吃', context: '💬 日常閒聊' },
  { thai: 'คนไทยใจดีมากค่ะ', pinyin: 'kon-tai jai-dii mâak kâ', zh: '泰國人很好心', context: '💬 日常閒聊' },
  { thai: 'จะกลับมาอีกค่ะ', pinyin: 'jà glàp maa ìik kâ', zh: '我還會再來', context: '💬 日常閒聊' },
  { thai: 'เหนื่อยมากเลยค่ะ', pinyin: 'nùeay mâak loey kâ', zh: '好累啊', context: '💬 日常閒聊' },
  { thai: 'หิวมากค่ะ', pinyin: 'hĭu mâak kâ', zh: '好餓', context: '💬 日常閒聊' },
  { thai: 'อิ่มแล้วค่ะ', pinyin: 'ìm láew kâ', zh: '吃飽了', context: '💬 日常閒聊' },
  { thai: 'สนุกมากเลยค่ะ', pinyin: 'sà-nùk mâak loey kâ', zh: '超好玩的', context: '💬 日常閒聊' },
  { thai: 'ประทับใจมากค่ะ', pinyin: 'bprà-tàp-jai mâak kâ', zh: '印象深刻', context: '💬 日常閒聊' },
  { thai: 'คิดถึงประเทศไทยค่ะ', pinyin: 'kít-tŭeng bprà-têet-tai kâ', zh: '好想念泰國', context: '💬 日常閒聊' },
  { thai: 'ถ่ายรูปสวยมากค่ะ', pinyin: 'tàai-rûup sŭay mâak kâ', zh: '照片拍得好漂亮', context: '💬 日常閒聊' },
  { thai: 'ยังไม่ได้ไปค่ะ', pinyin: 'yang mâi dâi bpai kâ', zh: '還沒去過', context: '💬 日常閒聊' },
  { thai: 'อยากลองค่ะ', pinyin: 'yàak lorng kâ', zh: '想試試看', context: '💬 日常閒聊' },
  { thai: 'ครั้งหน้าจะลองค่ะ', pinyin: 'kráng-nâa jà lorng kâ', zh: '下次再試', context: '💬 日常閒聊' },
  { thai: 'ชอบมากเลยค่ะ', pinyin: 'chôp mâak loey kâ', zh: '超喜歡的', context: '💬 日常閒聊' },
  { thai: 'ไม่ชอบเท่าไหร่ค่ะ', pinyin: 'mâi chôp tâo-rài kâ', zh: '不太喜歡', context: '💬 日常閒聊' },
  { thai: 'ดีใจมากที่ได้เจอค่ะ', pinyin: 'dii-jai mâak tîi dâi jer kâ', zh: '很高興見到你', context: '💬 日常閒聊' },
  { thai: 'ไว้เจอกันใหม่นะคะ', pinyin: 'wái jer-gan mài ná kâ', zh: '下次再見喔', context: '💬 日常閒聊' },

  // 🙏 泰國文化禮儀
  { thai: 'ไหว้ค่ะ', pinyin: 'wâi kâ', zh: '合十致意（wai）', context: '🙏 泰國文化禮儀' },
  { thai: 'ขอโทษที่รบกวนนะคะ', pinyin: 'kŏr-tôht tîi róp-guan ná kâ', zh: '不好意思打擾了', context: '🙏 泰國文化禮儀' },
  { thai: 'เข้าวัดต้องแต่งตัวยังไงคะ', pinyin: 'kâo wát dtông dtàeng-dtuay yang-ngai ká', zh: '進寺廟要怎麼穿著？', context: '🙏 泰國文化禮儀' },
  { thai: 'ถ่ายรูปได้ไหมคะ', pinyin: 'tàai-rûup dâi mái ká', zh: '可以拍照嗎？', context: '🙏 泰國文化禮儀' },
  { thai: 'ฉันเคารพวัฒนธรรมไทยค่ะ', pinyin: 'chăn kao-róp wát-tá-ná-tam tai kâ', zh: '我尊重泰國文化', context: '🙏 泰國文化禮儀' },
  { thai: 'ขอถ่ายรูปด้วยกันได้ไหมคะ', pinyin: 'kŏr tàai-rûup dûay-gan dâi mái ká', zh: '可以一起拍照嗎？', context: '🙏 泰國文化禮儀' },
  { thai: 'ห้ามเข้าค่ะ', pinyin: 'hâam kâo kâ', zh: '禁止進入', context: '🙏 泰國文化禮儀' },
  { thai: 'ขอบคุณสำหรับความเอื้อเฟื้อค่ะ', pinyin: 'kòp-kun săm-ràp kwaam-ûea-fúea kâ', zh: '感謝你的款待', context: '🙏 泰國文化禮儀' },
  { thai: 'สาธุค่ะ', pinyin: 'saa-tú kâ', zh: '阿門／祈願（佛教用語）', context: '🙏 泰國文化禮儀' },
  { thai: 'ทำบุญค่ะ', pinyin: 'tam-bun kâ', zh: '做功德', context: '🙏 泰國文化禮儀' },
  { thai: 'ขอโทษที่ไม่รู้ธรรมเนียมค่ะ', pinyin: 'kŏr-tôht tîi mâi rúu tam-niam kâ', zh: '抱歉我不懂習俗', context: '🙏 泰國文化禮儀' },
  { thai: 'ต้องถอดรองเท้าไหมคะ', pinyin: 'dtông tòt rong-táo mái ká', zh: '需要脫鞋嗎？', context: '🙏 泰國文化禮儀' },
  { thai: 'แต่งตัวแบบนี้เข้าวัดได้ไหมคะ', pinyin: 'dtàeng-dtuay bàep-níi kâo wát dâi mái ká', zh: '這樣穿可以進寺廟嗎？', context: '🙏 泰國文化禮儀' },
  { thai: 'ขอผ้าคลุมได้ไหมคะ', pinyin: 'kŏr pâa-klum dâi mái ká', zh: '可以借布遮身嗎？', context: '🙏 泰國文化禮儀' },
  { thai: 'ทำบุญได้ที่ไหนคะ', pinyin: 'tam-bun dâi tîi-nǎi ká', zh: '在哪裡可以做功德？', context: '🙏 泰國文化禮儀' },
  { thai: 'ใส่บาตรได้ที่ไหนคะ', pinyin: 'sài-bàat dâi tîi-nǎi ká', zh: '在哪裡可以托缽供僧？', context: '🙏 泰國文化禮儀' },
  { thai: 'วันพระคือวันไหนคะ', pinyin: 'wan prá kuue wan-nǎi ká', zh: '佛日是哪天？', context: '🙏 泰國文化禮儀' },
  { thai: 'สงกรานต์คือเทศกาลอะไรคะ', pinyin: 'sŏng-graan kuue têet-sà-gaan à-rai ká', zh: '宋干節是什麼節日？', context: '🙏 泰國文化禮儀' },
  { thai: 'ลอยกระทงคือเมื่อไหร่คะ', pinyin: 'loi grà-tong kuue mûuea-rài ká', zh: '水燈節是什麼時候？', context: '🙏 泰國文化禮儀' },
  { thai: 'ห้ามจับพระพุทธรูปไหมคะ', pinyin: 'hâam jàp prá-pút-tá-rûup mái ká', zh: '不能觸碰佛像嗎？', context: '🙏 泰國文化禮儀' },
  { thai: 'ห้ามชี้นิ้วไปที่พระไหมคะ', pinyin: 'hâam chîi níu bpai tîi prá mái ká', zh: '不能用手指指佛像嗎？', context: '🙏 泰國文化禮儀' },
  { thai: 'สีเหลืองคือสีของวันไหนคะ', pinyin: 'sĭi lŭuang kuue sĭi kŏng wan-nǎi ká', zh: '黃色是哪天的顏色？', context: '🙏 泰國文化禮儀' },
  { thai: 'เกรงใจหมายความว่าอะไรคะ', pinyin: 'greng-jai mǎai-kwaam wâa à-rai ká', zh: 'เกรงใจ 是什麼意思？', context: '🙏 泰國文化禮儀' },
  { thai: 'สบายๆหมายความว่าอะไรคะ', pinyin: 'sà-baai sà-baai mǎai-kwaam wâa à-rai ká', zh: 'สบายๆ 是什麼意思？', context: '🙏 泰國文化禮儀' },
  { thai: 'ไม่ควรพูดเรื่องอะไรบ้างคะ', pinyin: 'mâi kuuan pûut rûuang à-rai bâang ká', zh: '有什麼話題不應該聊？', context: '🙏 泰國文化禮儀' },
  { thai: 'เคารพสถาบันกษัตริย์ค่ะ', pinyin: 'kao-róp sà-tǎa-ban gà-sàt kâ', zh: '尊重王室', context: '🙏 泰國文化禮儀' },
  { thai: 'ขอบคุณสำหรับการต้อนรับค่ะ', pinyin: 'kòp-kun săm-ràp gaan dtôn-ráp kâ', zh: '謝謝你的歡迎', context: '🙏 泰國文化禮儀' },
  { thai: 'อาหารอร่อยมากค่ะ ขอบคุณมากเลย', pinyin: 'aa-hǎan à-ròi mâak kâ kòp-kun mâak loey', zh: '食物很好吃，非常感謝', context: '🙏 泰國文化禮儀' },
  { thai: 'บ้านสวยมากค่ะ', pinyin: 'bâan sŭay mâak kâ', zh: '你家好漂亮', context: '🙏 泰國文化禮儀' },
  { thai: 'ครอบครัวน่ารักมากค่ะ', pinyin: 'krôp-kruua nâa-rák mâak kâ', zh: '你的家人好可愛', context: '🙏 泰國文化禮儀' },

  // 💆 休閒娛樂
  { thai: 'นวดแรงๆหน่อยได้ไหมคะ', pinyin: 'nûat raeng-raeng nòi dâi mái ká', zh: '可以按重一點嗎？', context: '💆 休閒娛樂' },
  { thai: 'เบาๆหน่อยนะคะ', pinyin: 'bao-bao nòi ná kâ', zh: '輕一點喔', context: '💆 休閒娛樂' },
  { thai: 'นวดไทยราคาเท่าไหร่คะ', pinyin: 'nûat tai raa-kaa tâo-rài ká', zh: '泰式按摩多少錢？', context: '💆 休閒娛樂' },
  { thai: 'ซื้อตั๋วที่ไหนคะ', pinyin: 'súue dtǔa tîi-nǎi ká', zh: '在哪裡買票？', context: '💆 休閒娛樂' },
  { thai: 'ขอถ่ายรูปให้หน่อยได้ไหมคะ', pinyin: 'kŏr tàai-rûup hâi nòi dâi mái ká', zh: '可以幫我拍照嗎？', context: '💆 休閒娛樂' },
  { thai: 'กดปุ่มนี้นะคะ', pinyin: 'gòt bpùm níi ná kâ', zh: '按這個按鈕喔', context: '💆 休閒娛樂' },
  { thai: 'ถ่ายอีกทีได้ไหมคะ', pinyin: 'tàai ìik tii dâi mái ká', zh: '可以再拍一次嗎？', context: '💆 休閒娛樂' },
  { thai: 'เปิดกี่โมงคะ', pinyin: 'bpùet gìi moong ká', zh: '幾點開門？', context: '💆 休閒娛樂' },
  { thai: 'ปิดกี่โมงคะ', pinyin: 'bpìt gìi moong ká', zh: '幾點關門？', context: '💆 休閒娛樂' },
  { thai: 'มีส่วนลดสำหรับนักท่องเที่ยวไหมคะ', pinyin: 'mii sùan-lót săm-ràp nák-tông-tîao mái ká', zh: '有觀光客折扣嗎？', context: '💆 休閒娛樂' },
  { thai: 'อยากลองนวดไทยค่ะ', pinyin: 'yàak lorng nûat tai kâ', zh: '想試試泰式按摩', context: '💆 休閒娛樂' },
  { thai: 'นวดฝ่าเท้าราคาเท่าไหร่คะ', pinyin: 'nûat fàa-táo raa-kaa tâo-rài ká', zh: '腳底按摩多少錢？', context: '💆 休閒娛樂' },
  { thai: 'นวดน้ำมันราคาเท่าไหร่คะ', pinyin: 'nûat nám-man raa-kaa tâo-rài ká', zh: '精油按摩多少錢？', context: '💆 休閒娛樂' },
  { thai: 'จองนวดล่วงหน้าได้ไหมคะ', pinyin: 'jorng nûat lûuang-nâa dâi mái ká', zh: '可以提前預約按摩嗎？', context: '💆 休閒娛樂' },
  { thai: 'มีโปรโมชั่นไหมคะ', pinyin: 'mii proh-moh-chân mái ká', zh: '有促銷優惠嗎？', context: '💆 休閒娛樂' },
  { thai: 'ดูหนังอยากดูเรื่องอะไรคะ', pinyin: 'duu năng yàak duu rûuang à-rai ká', zh: '看電影想看什麼？', context: '💆 休閒娛樂' },
  { thai: 'มีซับไตเติ้ลภาษาอังกฤษไหมคะ', pinyin: 'mii sáp-tai-tûl paa-sǎa ang-grìt mái ká', zh: '有英文字幕嗎？', context: '💆 休閒娛樂' },
  { thai: 'ตลาดนัดอยู่ที่ไหนคะ', pinyin: 'dtà-làat-nát yùu tîi-nǎi ká', zh: '週末市集在哪裡？', context: '💆 休閒娛樂' },
  { thai: 'ถนนคนเดินเปิดกี่โมงคะ', pinyin: 'tà-nŏn kon dern bpùet gìi moong ká', zh: '步行街幾點開？', context: '💆 休閒娛樂' },
  { thai: 'ไนท์บาซาร์อยู่ที่ไหนคะ', pinyin: 'nait baa-sâa yùu tîi-nǎi ká', zh: '夜市在哪裡？', context: '💆 休閒娛樂' },
  { thai: 'กิจกรรมอะไรน่าสนุกบ้างคะ', pinyin: 'gìt-jà-gam à-rai nâa-sà-nùk bâang ká', zh: '有什麼有趣的活動？', context: '💆 休閒娛樂' },
  { thai: 'ทัวร์วันเดียวมีไหมคะ', pinyin: 'tuua wan-diao mii mái ká', zh: '有一日遊嗎？', context: '💆 休閒娛樂' },
  { thai: 'ล่องเรือได้ที่ไหนคะ', pinyin: 'lông-ruua dâi tîi-nǎi ká', zh: '在哪裡可以坐船？', context: '💆 休閒娛樂' },
  { thai: 'ดำน้ำได้ที่ไหนคะ', pinyin: 'dam-nám dâi tîi-nǎi ká', zh: '在哪裡可以潛水？', context: '💆 休閒娛樂' },
  { thai: 'เช่าจักรยานได้ที่ไหนคะ', pinyin: 'châo jàk-grà-yaan dâi tîi-nǎi ká', zh: '在哪裡可以租腳踏車？', context: '💆 休閒娛樂' },
  { thai: 'สปาดีๆแนะนำได้ไหมคะ', pinyin: 'sà-paa dii-dii náe-nam dâi mái ká', zh: '可以推薦好的 Spa 嗎？', context: '💆 休閒娛樂' },
  { thai: 'คาเฟ่น่ารักๆแนะนำได้ไหมคะ', pinyin: 'kaa-fée nâa-rák náe-nam dâi mái ká', zh: '可以推薦可愛的咖啡廳嗎？', context: '💆 休閒娛樂' },
  { thai: 'จุดถ่ายรูปสวยๆอยู่ที่ไหนคะ', pinyin: 'jùt tàai-rûup sŭay yùu tîi-nǎi ká', zh: '漂亮的拍照景點在哪裡？', context: '💆 休閒娛樂' },
  { thai: 'ร้านนี้ดังเรื่องอะไรคะ', pinyin: 'ráan níi dang rûuang à-rai ká', zh: '這家店以什麼出名？', context: '💆 休閒娛樂' },
  { thai: 'มีโชว์การแสดงไหมคะ', pinyin: 'mii choh gaan-sà-daeng mái ká', zh: '有表演秀嗎？', context: '💆 休閒娛樂' },

  // 🔢 數字 & 時間
  { thai: 'ตอนนี้กี่โมงคะ', pinyin: 'dton-níi gìi moong ká', zh: '現在幾點？', context: '🔢 數字 & 時間' },
  { thai: 'วันนี้วันที่เท่าไหร่คะ', pinyin: 'wan-níi wan-tîi tâo-rài ká', zh: '今天幾號？', context: '🔢 數字 & 時間' },
  { thai: 'นัดกี่โมงดีคะ', pinyin: 'nát gìi moong dii ká', zh: '約幾點好？', context: '🔢 數字 & 時間' },
  { thai: 'รอสักห้านาทีนะคะ', pinyin: 'ror sàk hâa naa-tii ná kâ', zh: '等我五分鐘', context: '🔢 數字 & 時間' },
  { thai: 'ราคารวมทั้งหมดเท่าไหร่คะ', pinyin: 'raa-kaa ruam táng-mòt tâo-rài ká', zh: '總共多少錢？', context: '🔢 數字 & 時間' },
  { thai: 'แบงค์พันมีไหมคะ', pinyin: 'baeng pan mii mái ká', zh: '有千元鈔嗎？', context: '🔢 數字 & 時間' },
  { thai: 'ขอทอนด้วยค่ะ', pinyin: 'kŏr ton dûay kâ', zh: '請找零', context: '🔢 數字 & 時間' },
  { thai: 'อีกนานไหมคะ', pinyin: 'ìik naan mái ká', zh: '還要很久嗎？', context: '🔢 數字 & 時間' },
  { thai: 'มาถึงกี่โมงคะ', pinyin: 'maa-tŭeng gìi moong ká', zh: '幾點到？', context: '🔢 數字 & 時間' },
  { thai: 'เปิดทุกวันไหมคะ', pinyin: 'bpùet túk wan mái ká', zh: '每天都開嗎？', context: '🔢 數字 & 時間' },
  { thai: 'หนึ่ง สอง สาม สี่ ห้า', pinyin: 'nùeng sŏng săam sìi hâa', zh: '一 二 三 四 五', context: '🔢 數字 & 時間' },
  { thai: 'หก เจ็ด แปด เก้า สิบ', pinyin: 'hòk jèt bpàet gâo sìp', zh: '六 七 八 九 十', context: '🔢 數字 & 時間' },
  { thai: 'ร้อย พัน หมื่น แสน ล้าน', pinyin: 'rói pan mùuen sǎen láan', zh: '百 千 萬 十萬 百萬', context: '🔢 數字 & 時間' },
  { thai: 'วันนี้วันจันทร์ค่ะ', pinyin: 'wan-níi wan-jan kâ', zh: '今天是星期一', context: '🔢 數字 & 時間' },
  { thai: 'พรุ่งนี้วันอังคารค่ะ', pinyin: 'prûng-níi wan-ang-kaan kâ', zh: '明天是星期二', context: '🔢 數字 & 時間' },
  { thai: 'เมื่อวานวันพุธค่ะ', pinyin: 'mûuea-waan wan-pút kâ', zh: '昨天是星期三', context: '🔢 數字 & 時間' },
  { thai: 'วันศุกร์ไปเที่ยวค่ะ', pinyin: 'wan-sùk bpai tîao kâ', zh: '星期五去玩', context: '🔢 數字 & 時間' },
  { thai: 'เดือนนี้เดือนอะไรคะ', pinyin: 'duuean-níi duuean à-rai ká', zh: '這個月是幾月？', context: '🔢 數字 & 時間' },
  { thai: 'ปีนี้ปีอะไรคะ', pinyin: 'bpii-níi bpii à-rai ká', zh: '今年是哪一年？', context: '🔢 數字 & 時間' },
  { thai: 'เกิดวันที่เท่าไหร่คะ', pinyin: 'gùet wan-tîi tâo-rài ká', zh: '你幾號生日？', context: '🔢 數字 & 時間' },
  { thai: 'สุขสันต์วันเกิดค่ะ', pinyin: 'sùk-săn wan-gùet kâ', zh: '生日快樂', context: '🔢 數字 & 時間' },
  { thai: 'เมื่อกี้กี่โมงคะ', pinyin: 'mûuea-gîi gìi moong ká', zh: '剛才幾點？', context: '🔢 數字 & 時間' },
  { thai: 'อีกนานแค่ไหนคะ', pinyin: 'ìik naan kâe nǎi ká', zh: '還要多久？', context: '🔢 數字 & 時間' },
  { thai: 'ใช้เวลากี่ชั่วโมงคะ', pinyin: 'chái weh-laa gìi chûua-moong ká', zh: '需要幾個小時？', context: '🔢 數字 & 時間' },
  { thai: 'ครึ่งชั่วโมงก็ถึงค่ะ', pinyin: 'krûeng chûua-moong gôr tŭeng kâ', zh: '半小時就到了', context: '🔢 數字 & 時間' },
  { thai: 'เปิดทำการกี่วันคะ', pinyin: 'bpùet tam-gaan gìi wan ká', zh: '一週開幾天？', context: '🔢 數字 & 時間' },
  { thai: 'หยุดวันไหนคะ', pinyin: 'yùt wan-nǎi ká', zh: '哪天休息？', context: '🔢 數字 & 時間' },
  { thai: 'นัดกันวันเสาร์ได้ไหมคะ', pinyin: 'nát gan wan-săo dâi mái ká', zh: '可以約星期六嗎？', context: '🔢 數字 & 時間' },
  { thai: 'มาสายนิดหน่อยค่ะ ขอโทษด้วยนะคะ', pinyin: 'maa săai nít-nòi kâ kŏr-tôht dûay ná kâ', zh: '我會晚一點到，抱歉', context: '🔢 數字 & 時間' },
  { thai: 'ตรงเวลาค่ะ', pinyin: 'dtrong weh-laa kâ', zh: '準時', context: '🔢 數字 & 時間' },
]

export function getTodaySentence(date: Date = new Date()): DailySentence {
  const startOfYear = new Date(date.getFullYear(), 0, 0).getTime()
  const dayOfYear = Math.floor((date.getTime() - startOfYear) / 86400000)
  return DAILY_SENTENCES[dayOfYear % DAILY_SENTENCES.length]
}
